export const options = [
  "character_id",
  "character_name",
  "gender",
  "status",
  "specie",
  "subspecie",
  "id_origin",
  "id_last_location",
  "location_id",
  "location_name",
  "location_type",
  "dimension",
  "episode_id",
  "episode_name",
  "episode_code",
  "air_date",
];
